# Generated by Django 4.2.6 on 2023-11-15 14:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('anketa', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Sertif',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('osnnavik', models.IntegerField(blank=True, default='0', null=True, verbose_name='Основной навык')),
                ('vsenavik', models.IntegerField(blank=True, default='0', null=True, verbose_name='Все навыки')),
                ('data', models.DateTimeField(verbose_name='Дата')),
                ('itog', models.FileField(max_length=255, upload_to='', verbose_name='Сертификат')),
                ('polzovatel', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='anketa.grazhdanin', verbose_name='Пользователь')),
                ('sertif', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='anketa.sertifikat', verbose_name='Сертификат')),
            ],
            options={
                'verbose_name': 'Сертификат',
                'verbose_name_plural': 'Сертификаты',
                'ordering': ['-polzovatel'],
            },
        ),
        migrations.CreateModel(
            name='Otvet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ball', models.IntegerField(blank=True, default='0', null=True, verbose_name='Баллы')),
                ('data', models.DateTimeField(verbose_name='Дата')),
                ('navik', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='anketa.naviki', verbose_name='Навык')),
                ('polzovatel', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='anketa.grazhdanin', verbose_name='Пользователь')),
            ],
            options={
                'verbose_name': 'Ответ',
                'verbose_name_plural': 'Ответ',
                'ordering': ['-id'],
            },
        ),
    ]
